language: erlang
otp_release:
  - 17.4
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.3.zip
  - unzip -d elixir v1.0.3.zip
before_script:
  - "export PATH=`pwd`/elixir/bin:$PATH"
  - "mix local.hex --force"
  - "mix deps.get"
script: mix test
after_script:
  - mix coveralls.travis
  - mix deps.get
  - mix inch.report
notifications:
  recipients:
    - a@songe.me
